# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_quiz', '0003_auto_20170609_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='exams',
            new_name='quizzes',
        ),
    ]
