# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_quiz', '0006_auto_20170609_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='Misc', help_text='<br /> Try to fit in 128 characters', max_length=128, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='quizzes',
            field=models.ManyToManyField(help_text='<br /> Quizzes related to this group.', related_name='quizzes', to='simple_quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(help_text='<br />Leave blank for auto-generated slug.', unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(help_text='<br />Try to fit in 256 characters', max_length=256, verbose_name='Title'),
        ),
    ]
